--sudo -u postgres psql < database/initialize-decks.sql

INSERT INTO
  decks(color_id, deck_name, commander, theme, constructed, flagged, feedback)
VALUES
  ('WUBRG', 'Sliver Cascade', 'The First Sliver',  'Sliver Tribal', true, false, null),
  ('WUBRG', 'EverQuest', 'Kenrith', 'Experience/Counters/Poison', true, false, null),
  ('WUBR', 'Ambient Artifact Assault', 'Akiri and Silas', 'Artifact Resonance', true, false, null),
  ('WUBR', 'Fire Riders', 'Cecily and Sophina', 'Non-permanents', false, true, null),
  ('GWUB', 'Super Friends', 'Atraxa, Praetors Voice', 'Planeswalkers/Proliferation', true, true, null),
  ('GWUB', 'Redless', null, null, false, false, null),
  ('RGWU', 'Meletis, Realm of Chaos', 'Kynaios and Tiro of Meletis', 'Chaos/Group Hug', true, false, null),
  ('RGWU', 'Blackless', null, null, false, false, null),
  ('BRGW', 'Road Rage', 'Saskia, The Unyielding', 'Cheat Monster Into Play', true, false, null),
  ('BRGW', 'Blueless', null, null, false, false, null),
  ('UBRG', 'Patient Partnership', 'Smasher and Thrasios', 'CMC Damage', true, false, null),
  ('UBRG', 'Whiteless', null, null, false, false, null),
  ('WUB', 'Life Gain and Drain', 'Oloro', 'Lifegain, lifedrain', true, false, null),
  ('WUB', 'Esper', null, null, false, false, null),
  ('URW', 'Bad Gifts', 'Zedruu', 'Bad Gifts', true, false, null),
  ('URW', 'Whenever Whatever', 'Ishai and Kediss', 'Whenever Opponent Triggers', true, false, null),
  ('GWU', 'Death From Above', 'Derevi', 'Flyers and Stax', true, false, null),
  ('GWU', 'Bant', null, null, false, false, null),
  ('RWB', 'Game of Thrones', 'Queen Marchesa', 'Politics and Rattlesnakes', true, false, null),
  ('RWB', 'Mardu', null, null, false, false, null),
  ('WBG', 'Abzan Clan Token Plan', 'Ghave', 'Tokens. Lots of Tokens', true, false, null),
  ('WBG', 'Abzan Clan No Plan', null, null, false, false, null),
  ('RGW', 'The Relentless', 'Marisi', 'Repeated Combat Phases/Goading', true, true, 'Primal Surge?'),
  ('RGW', 'Naya', null, null, false, false, null),
  ('UBR', 'Curses Like Candy', 'Lynde', 'Curses/Goading', true, false, null),
  ('UBR', 'Grixis', null, null, false, false, null),
  ('UGB', 'Graverider', 'Muldrotha', 'Discard', true, false, null),
  ('UGB', 'Sultai', null, null, false, false, null),
  ('RUG', 'The Artists', 'Kydela and Jeska', 'Draw Triggers', true, false, null),
  ('RUG', 'Temur', null, null, false, false, null),
  ('BRG', 'Asymetrical Sacrifice', 'Shattergang', 'Sacrifice', true, false, null),
  ('BRG', 'Jund', null, null, false, false, null),
  ('WU', 'Fast Lane', 'Shorikai', 'Vehicles', true, false, null),
  ('WU', 'Azorius', null, null, false, false, null),
  ('WB', 'Liesa, Eternal Exiler', 'Liesa', 'Exile', true, false, null),
  ('WB', 'Oppressive Auras', 'Eriette?', 'Oppressive Auras', false, true, null),
  ('RW', 'Ghost Clones', 'Hofri', 'Ghost Clones', true, false, null),
  ('RW', 'Boros', null, null, false, false, null),
  ('GW', 'Aura Assault', 'Sigarda', 'Aura Assault', true, true, 'Eldraine Roles/Auras'),
  ('GW', 'Selesnya', null, null, false, false, null),
  ('UB', 'Horrific Nightmares', 'Umbris', 'Deck Exile/Fear Tribal', true, true, 'Hull Crasher/Eldraine'),
  ('UB', 'Dimir', null, null, false, false, null),
  ('UR', 'Mistress of Suspense', 'Jhoira', 'Suspend/Counterspell', true, false, null),
  ('UR', 'Controlled Chaos', 'Okaun and Zndrslpt', 'Flips/Rolls/Chaos', true, false, null),
  ('GU', 'Clones', 'Esix', 'Clones', true, false, null),
  ('GU', 'Simic', null, null, false, false, null),
  ('BR', 'Mogis The Bogus', 'Mogis', 'Extreme Creature Hate/Stax', true, false, null),
  ('BR', 'Rakdos', null, null, false, false, null),
  ('BG', 'Skullbriar', 'Skullbriar', 'Counter Voltron', true, true, 'Agatha Soul Cauldron?'),
  ('BG', 'Golgari', null, null, false, false, null),
  ('RG', 'The One Hit Wonder Wurm', 'Thromok', 'Devour Monster/Tokens', true, false, null),
  ('RG', 'Messing Up Everything', 'Agatha', 'Discounted abilities', false, true, null),
  ('W', 'Legendary Creature', 'Giada', 'Angel Tribal', true, false, null),
  ('W', 'White', null, null, false, false, null),
  ('U', 'Witness Oblivion', 'Atemsis', 'CMC Diversity', true, false, null),
  ('U', 'Blue', null, null, false, false, null),
  ('B', 'Rats Rises', 'Marrow-Gnawer', 'Rat Tribal/Construction Exception', true, false, null),
  ('B', 'Black', null, null, false, false, null),
  ('R', 'Reckless Burn', 'Hidetsugu', 'Asymetric Burn', true, false, null),
  ('R', 'Red', null, null, false, false, null),
  ('G', 'History of Card Draw', 'Reki', 'Legendaries', true, true, 'Reki => Titania/Omnath?'),
  ('G', 'Green', 'Reki/Titania/Omnath', null, false, false, null),
  ('C', 'The End Is Nigh', 'Emrakul', 'Card Type Diversity', true, false, null),
  ('C', 'Artifact Attack', 'Gynger', 'Artifacts', true, false, null);